apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: europe-west3-docker.pkg.dev/cloud-abgabe/cloud-project-registry/cloud-project-auth:v0.1
          ports:
          - containerPort: 4000
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: CLIENT_SECRET
      imagePullSecrets:
      - name: regcred